version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    ignore: all
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    ignore: all
